template = '''
apiVersion: v1
kind: Pod
metadata:
  name: terraform
  labels:
    run: terraform
spec:
  containers:
  - name: terraform
    image: hashicorp/terraform
    command:
    - sleep
    - "3600"
'''

properties([
  parameters([
    choice(choices: ['apply', 'destroy'], description: 'Please select action ', name: 'choice')
                       ])
           ])

podTemplate(cloud: 'kubernetes', label: 'terraform', yaml: template ) {
        node ("terraform") {
        container("terraform") {
        stage ("Pull code") {
        git branch: 'main', url: 'https://github.com/kazakbaevelaman/jenkins-2024.git'
        }
   
        withCredentials([usernamePassword(credentialsId: 'aws-creds', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
        stage ("Init") {
            sh """ 
            cd terraform 
            terraform init 
            """
            }

          if (params.choice == "apply") {
            stage ("Apply") {
            sh """cd terraform
            terraform apply -auto-approve
            """
              }
            }
            
          else {
            stage ("Destroy") {
            sh """cd terraform
            terraform destroy -auto-approve
            """
            }
          }
      
        }
    }
  }
}


